### ISSUE TITLE
Question regarding default highlight animation function

### ISSUE THREAD

**Issue by eXhumer** [tallbl0nde/Aether#4]
https://github.com/tallbl0nde/Aether/blob/d8effd1f8f5776cb3b962a81394365fd11660c29/source/Display.cpp#L273

While main loop for display is running, the display's clock last tick value is passed to animation function and called. But nothing is going to happen with it since by default, the highlight animation does nothing with the passed value.

https://github.com/tallbl0nde/Aether/blob/d8effd1f8f5776cb3b962a81394365fd11660c29/source/Display.cpp#L39

Here a `uint32_t` value is accepted but nothing is done with it.

Are there any plans to do anything with the value of `t` with default highlight animation function? Or are you keeping it like this for custom highlight animation function implementation?

**Comment by tallbl0nde** [comment]
Yeah it's there so people can have it animate over time instead of having a hardcoded option. The default function is just left there so it doesn't crash if the dev doesn't provide a function. I didn't want to have a default animation when I wrote it (I don't know why), although I do provide some in utils/Theme.hpp such as this one: 

https://github.com/tallbl0nde/Aether/blob/d8effd1f8f5776cb3b962a81394365fd11660c29/include/utils/Theme.hpp#L25-L30

Like I said before there are a lot of weird things that I've done so don't hesitate to bring more things up :)

**Comment by eXhumer** [comment]
TY for the response.

Closed as it was answered.
